class Consts:
    # ? Display & Video Settings
    ALGO_FRAME_WIDTH = 640
    ALGO_FRAME_HEIGHT = 480
    VIDEO_FPS = 30
    VIDEO_FOURCC = 0
    REAL_FPS = 25
    DEFAULT_FRAME_WIDTH = 1280
    DEFAULT_FRAME_HEIGHT = 720
    DEFAULT_FRAME_RATE = 30


    # ? Preprocessing Parameters
    IFOV = 0.686314
    RESIZE_FACTOR = 2.25
    PADDING_CENTER_DIVISOR = 2
    DEFAULT_PADDING_COLOR = (114, 114, 114)
    RGB_NUM_OF_COLORS = 3

    # ? Pose Model Configuration
    CLASS_NAME_FOR_MODEL = 1
    POSE_MAX_DETECTIONS = 300
    POSE_SCORE_THRESHOLD = 0.5
    POSE_NMS_IOU_THRESHOLD = 0.7
    POSE_REGRESSION_LENGTH = 15
    POSE_STRIDES = [8, 16, 32]

    # ? Distance Estimation
    MIN_DISTANCE_THRESHOLD = 500
    AVG_DISTANCE_THRESHOLD = 0.5
    DISTANCE_M_TO_MM_FACTOR = 1000
    DIVIDING_FACTOR_TO_CHILD_VALUE = 1.3

    # ? Drawing Settings
    POSE_DRAWING_COLOR = (0, 255, 0)
    MIN_CONFIDENCE_FOR_DRAWING = 0.3
    JOINT_CIRCLE_RADIUS = 4
    SKELETON_LINE_THICKNESS = 2
    JOINT_CIRCLE_FILL_VALUE = -1

    # ? Confidence Thresholds
    DEFAULT_JOINT_CONFIDENCE = 0
    MIN_CONFIDENCE_THRESHOLD = 0.6

    # ? Timing
    SECONDS_TO_OPEN_PIPELINE = 10
    MILLISECONDS_FOR_OPEN_CAP = 0.5
